### ISSUE TITLE
Error validating test apps: 'version'

### ISSUE THREAD

**Issue by Res260** [splunk/contentctl#295]
I'm trying to get contentctl to download apps from splunkbase, but there is no documentation as to how to do that, so I have to keep guessing, but I'm running out of ideas.

Here is my command: `contentctl test --verbose mode:all`

Here is my `contentctl.yml`:

```yaml
splunk_api_username: someone@someone.com
splunk_api_password: hihi
version: 20240925.16.111
path: .
app:
  uid: 42123
  title: 'MyAPP'
  appid: myapp
  version: 20240925.16.111
  description: "MyAPP"
  prefix: MA
  label: 'MyAPP'
  author_name: "MyAPP"
  author_email: MyAPP@MyAPP.com
  author_company: "MyAPP"
verbose: false
enrichments: false
build_app: true
build_api: false
build_ssa: false
build_path: dist
mode: {}
post_test_behavior: pause_on_failure
enable_integration_testing: false
apps:
- uid: 263
  title: Enterprise Security
  appid: Splunk_Enterprise_Security
  version: 7.3.2
  description: Splunk Enterprise Security
- uid: 1621
  title: Splunk Common Information Model (CIM)
  appid: Splunk_SA_CIM
  version: 5.2.0
  description: Splunk Common Information Model
  hardcoded_path: https://attack-range-appbinaries.s3.us-west-2.amazonaws.com/Latest/splunk-common-information-model-cim_520.tgz
- uid: 5579
  title: Splunk Add-on for CrowdStrike FDR
  appid: Splunk_TA_CrowdStrike_FDR
  version: 1.5.0
  description: description of app
  hardcoded_path: https://attack-range-appbinaries.s3.us-west-2.amazonaws.com/Latest/splunk-add-on-for-crowdstrike-fdr_150.tgz
container_settings:
  leave_running: true
  num_containers: 1
  full_image_path: registry.hub.docker.com/splunk/splunk:latest
```

I get this error: 

```
Error validating 'contentctl.yml':
Error validating test apps: 'version'
```

It doesn't matter if I remove the `version` key from the contentctl.yml file, the error is the same.

Is this a bug or I'm doing something wrong?
