### ISSUE TITLE
This detection is required to have 2 drilldown_searches, but only has [0]

### ISSUE THREAD

**Issue by Res260** [splunk/contentctl#312]
Hi, I updated contentctl to 4.4.0 from 4.2.2, and I now have brand new errors. One of them is:

`This detection is required to have 2 drilldown_searches, but only has [0]`

When I run `contentctl test --enable-integration-testing --verbose mode:all`.

I tried searching for documentation and found nothing. I checked source code, this error comes from this commit 9ba93009 which states 

> Add the possibility to automatically create drilldowns. We will likely remove this, but let's keep it now for purposes of discussion.

Since the commit message says "the possibility", this seems to imply that enforcing this is a mistake?

In any case I'm very lost and don't know how to deal with this error. Some documentation and/or guidance would be appreciated :) 

Thanks!

**Comment by Res260** [comment]
An ugly but working workaround is to add this snippet to a Detection YAML:

```yaml
drilldown_searches:
- earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
  name: DummyDrilldown1
  search: '%original_detection_search%'
- earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
  name: DummyDrilldown2
  search: '%original_detection_search%'
```
